### ISSUE TITLE
Travis API changed for URLs

### ISSUE THREAD

**Issue by Zomis** [skiwi2/GithubHookSEChatService#48]
The Travis API seems to have changed for URLs as it now outputs:

`[[Cardshifter/Cardshifter](null)] build #625 for commit [e0025d87](null/commit/e0025d877f9c477799a6d7c0472974483bb7e4fa) on branch [javafx](null/tree/javafx) passed`

**Comment by Zomis** [comment]
A workaround patch can be found here: https://github.com/Zomis/GithubHookSEChatService/commit/64351bdf6ff557d6c5eb82fc4389545f6b1fdc94 (not that the commit is on a branch with some other added functionality as well)

It still breaks when synchronizing pull requests though, but that is an easy fix

**Comment by Zomis** [comment]
This has now been fixed in my fork

**Comment by skiwi2** [comment]
It seems to be that the repository url did not mean what we thought it meant.

The field gets populated from the custom repository url setting in GitHub, which can be your home page site for the reference. It seems like GitHub used to use the actual url to the repository if nothing was present (the default), but then they decided that it should return null.

A more in depth explanation can be seen here: https://github.com/travis-ci/travis-ci/issues/2935#issuecomment-74294802

Anyway, the issue has been fixed and there is no need to look at repository.url again.
